## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/bing-api"
  to = "https://cn.bing.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/weather"
  to = "https://tianqiapi.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}